version: '3'
services:
  postgres:
    image: postgres:12.11-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    container_name: exercise-postgres